name: PHP TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test_7_1:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:7.1
    steps:
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.1.xml
  test_7_2:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:7.2
    steps:
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.2.xml
  test_7_3:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:7.3
    steps:
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.3.xml
  test_7_4:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:7.4
    steps:
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.4.xml
  test_8_0:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:8.0
    steps:
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_8.0.xml
  test_8_1:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:8.1
    steps:
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_8.1.xml
  test_8_2:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:8.2
    steps:
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_8.2.xml
